#!/usr/bin/gnuplot -persist
unset key
set view map scale 1
set style data lines
set xtics border in scale 0,0 mirror norotate  autojustify
set ytics border in scale 0,0 mirror norotate  autojustify
set ztics border in scale 0,0 nomirror norotate  autojustify
unset cbtics
set rtics axis in scale 0,0 nomirror norotate  autojustify
set title "Heat Map generated by 'plot' from a stream of XYZ values\nNB: Rows must be separated by blank lines!" 
set xrange [ 0.0 : 1024.0 ] noreverse nowriteback
set yrange [ 0 : 1024 ] noreverse nowriteback
set cblabel "Score" 
set cbrange [ 0.00000 : 0.000001 ] noreverse nowriteback
##set palette rgbformulae -7, 2, -7
set palette defined (0 0 0 0.5, 1 0 0 1, 2 0 0.5 1, 3 0 1 1, 4 0.5 1 0.5, 5 1 1 0, 6 1 0.5 0, 7 1 0 0, 8 0.5 0 0)
x = 0.0
splot "data_cpu.dat" using 1:2:3 with image
